#include <iostream>

#include "docxcpp/document.hpp"

int main() {
  docxcpp::Document document;
  docxcpp::RunStyle title_style;
  title_style.bold = true;
  title_style.font_size_pt = 18;
  title_style.color_hex = "336699";
  title_style.font_name = "Arial";
  title_style.highlight = "yellow";
  document.add_styled_heading("C++ DOCX Demo", 0, title_style,
                              docxcpp::ParagraphAlignment::Center);
  document.set_page_size_pt(595, 842);
  docxcpp::PageMargins margins;
  margins.top_pt = 72;
  margins.right_pt = 54;
  margins.bottom_pt = 72;
  margins.left_pt = 54;
  document.set_page_margins_pt(margins);
  document.add_paragraph("It was a dark and stormy night.");
  document.add_page_break();
  docxcpp::RunStyle body_style;
  body_style.italic = true;
  body_style.underline = true;
  body_style.font_size_pt = 12;
  body_style.color_hex = "#AA2200";
  body_style.font_name = "Courier New";
  body_style.highlight = "green";
  document.add_styled_paragraph("This file was generated by the C++ port.\nWith inline styling.",
                                body_style,
                                docxcpp::ParagraphAlignment::Right);
  document.add_heading("Table Sample", 1);
  document.add_table(2, 2);
  document.set_table_cell(0, 0, 0, "Top Left");
  document.set_table_cell(0, 1, 1, "Bottom Right");
  document.add_table_cell_paragraph(0, 1, 1, "Second cell paragraph");
  document.merge_table_cells(0, 0, 0, 0, 1);
  docxcpp::PictureSize image_size;
  image_size.width_pt = 72;
  image_size.height_pt = 36;
  document.add_picture(
      "/Users/yunxingluoyun/python-docx-master/features/steps/test_files/test.png", image_size);
  docxcpp::PictureSize cell_image_size;
  cell_image_size.width_pt = 36;
  cell_image_size.height_pt = 36;
  document.add_picture_to_table_cell(
      0, 1, 1, "/Users/yunxingluoyun/python-docx-master/features/steps/test_files/test.png",
      cell_image_size);
  document.save("dark-and-stormy-cpp.docx");

  const auto paragraphs = document.paragraphs();
  for (const auto& paragraph : paragraphs) {
    std::cout << paragraph.text() << '\n';
  }
  std::cout << "images=" << document.image_count() << '\n';

  return 0;
}
