if(NOT DEFINED DOCXCPP_SOURCE_DIR)
  message(FATAL_ERROR "DOCXCPP_SOURCE_DIR is required")
endif()

if(NOT DEFINED DOCXCPP_BINARY_DIR)
  message(FATAL_ERROR "DOCXCPP_BINARY_DIR is required")
endif()

set(DOCXCPP_INSTALL_PREFIX "${DOCXCPP_BINARY_DIR}/package-smoke/install")
set(DOCXCPP_CONSUMER_SOURCE_DIR "${DOCXCPP_SOURCE_DIR}/tests/package_smoke")
set(DOCXCPP_CONSUMER_BINARY_DIR "${DOCXCPP_BINARY_DIR}/package-smoke/build")
set(DOCXCPP_CONSUMER_OUTPUT "${DOCXCPP_CONSUMER_BINARY_DIR}/package-smoke.docx")

file(REMOVE_RECURSE "${DOCXCPP_INSTALL_PREFIX}" "${DOCXCPP_CONSUMER_BINARY_DIR}")
file(MAKE_DIRECTORY "${DOCXCPP_INSTALL_PREFIX}")

set(DOCXCPP_INSTALL_COMMAND
    "${CMAKE_COMMAND}" --install "${DOCXCPP_BINARY_DIR}" --prefix "${DOCXCPP_INSTALL_PREFIX}")
if(DOCXCPP_BUILD_CONFIG)
  list(APPEND DOCXCPP_INSTALL_COMMAND --config "${DOCXCPP_BUILD_CONFIG}")
endif()
execute_process(
  COMMAND ${DOCXCPP_INSTALL_COMMAND}
  RESULT_VARIABLE DOCXCPP_INSTALL_RESULT
)
if(NOT DOCXCPP_INSTALL_RESULT EQUAL 0)
  message(FATAL_ERROR "failed to install docxcpp package")
endif()

set(DOCXCPP_CONFIGURE_COMMAND
    "${CMAKE_COMMAND}"
    -S "${DOCXCPP_CONSUMER_SOURCE_DIR}"
    -B "${DOCXCPP_CONSUMER_BINARY_DIR}"
    "-DCMAKE_PREFIX_PATH=${DOCXCPP_INSTALL_PREFIX}")
execute_process(
  COMMAND ${DOCXCPP_CONFIGURE_COMMAND}
  RESULT_VARIABLE DOCXCPP_CONFIGURE_RESULT
)
if(NOT DOCXCPP_CONFIGURE_RESULT EQUAL 0)
  message(FATAL_ERROR "failed to configure installed-package consumer")
endif()

set(DOCXCPP_BUILD_COMMAND
    "${CMAKE_COMMAND}" --build "${DOCXCPP_CONSUMER_BINARY_DIR}")
if(DOCXCPP_BUILD_CONFIG)
  list(APPEND DOCXCPP_BUILD_COMMAND --config "${DOCXCPP_BUILD_CONFIG}")
endif()
execute_process(
  COMMAND ${DOCXCPP_BUILD_COMMAND}
  RESULT_VARIABLE DOCXCPP_BUILD_RESULT
)
if(NOT DOCXCPP_BUILD_RESULT EQUAL 0)
  message(FATAL_ERROR "failed to build installed-package consumer")
endif()

set(DOCXCPP_CONSUMER_EXE "${DOCXCPP_CONSUMER_BINARY_DIR}/docxcpp_package_smoke")
if(WIN32)
  set(DOCXCPP_CONSUMER_EXE "${DOCXCPP_CONSUMER_EXE}.exe")
endif()

execute_process(
  COMMAND "${DOCXCPP_CONSUMER_EXE}"
  WORKING_DIRECTORY "${DOCXCPP_CONSUMER_BINARY_DIR}"
  RESULT_VARIABLE DOCXCPP_RUN_RESULT
)
if(NOT DOCXCPP_RUN_RESULT EQUAL 0)
  message(FATAL_ERROR "failed to run installed-package consumer")
endif()

if(NOT EXISTS "${DOCXCPP_CONSUMER_OUTPUT}")
  message(FATAL_ERROR "installed-package consumer did not produce package-smoke.docx")
endif()
